# Exploracion de la estructura de los datos.
Lo primero que hicimos fue analizar y explorar los datos y la estructura del archivo mediante diferentes funciones de la libreria pandas.  

**Funciones y atributos utilizados:**  
**1.-read_csv:** Lectura del archivo mediante pandas.  
**2.- Skiprows:** Realiza saltos de linea del archivo. Lo utilizamos ya que las primeras lineas del txt tienen informacion adicional al Data Frame. Los registros comienzan en la linea 20.  
**3.- Skipfooter:** Al contrario de skiprows, skipfooter hace los saltos empezando de la ultima linea del archivo. Lo utilizamos ya que el ultimo registro tiene guiones en vez de datos.  
**4.- Names:** Mediante una lista asigna los nombres de las columnas.  
**5.- Sep:** Se utiliza para definir un delimitador entre columnas. Lo utilizamos ya que pandas tomaba las columnas de names como columnas independientes y les asignaba nulos a todos los registros. \s+ es para espacios en blanco.  
**6.-na_values** Sirve para indicar que una cadena es de tipo NaN. Le indicamos que los registros con el dato 'Nulo' contaran como nules. Esto solo para el analisis del archivo por lo que no modifica el dataframe.  
**7.- info():** Muestra un resumen del dataframe. Datos como el numero de registros, nombres de columna, tipos de dato, cantidad de nulos etc.  
**8.- shape:** Devuelve una tupla con las dimensiones del data frame (numero de filas y columnas).  
**9.- head():** Regresa las primeras filas del data frame.  
**10.- tail():** Muestra las ultimas filas del data frame.  
**11.- isnull().sum():** Hace la suma de todos los nulos por cada columna tambien muestra tipo de dato.  
**12.- nunique():** Devuelve la cantidad de registors unicos por cada columna.

Lectura de archivos mediante pandas:

In [ ]:
#Importacion de pandas y lectura del archivo.
import pandas as pd
df=pd.read_csv('Dataset/25001.txt',
skiprows=19, #saltamos las primeras 18 lineas del archivo
skipfooter=1,#saltamos la ultima linea 
names=['FECHA','PRECIP','EVAP','TMAX','TMIN'] , #Nombres de las columnas 
sep='\s+',#Separamos las columnas correctamente 
na_values='Nulo', #Asignamos como nulos los datos que contengan 'Nulo'
) 
df

<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
C:\Users\luis_\AppData\Local\Temp\ipykernel_28120\1650391941.py:7: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',#Separamos las columnas correctamente
C:\Users\luis_\AppData\Local\Temp\ipykernel_28120\1650391941.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df=pd.read_csv('Dataset/25001.txt',

            FECHA  PRECIP  EVAP  TMAX  TMIN
0      01/01/1961     0.0   NaN  25.0  13.0
1      02/01/1961     0.0   NaN  27.5  14.0
2      03/01/1961     0.0   NaN  31.0  11.0
3      04/01/1961     0.0   NaN  32.0  13.0
4      05/01/1961     0.0   NaN  29.0  14.0
...           ...     ...   ...   ...   ...
19569  27/07/2018     2.3   0.6  37.0  19.0
19570  28/07/2018     9.8   3.7  37.0  23.5
19571  29/07/2018     6.0   3.3  35.0  20.0
19572  30/07/2018    48.0   6.0  36.0  22.0
19573  31/07/2018     2.0   3.7  34.0  22.0

[19574 rows x 5 columns]

El Data Frame tiene un total 19574 registros, 5 columnas (FECHA, PRECIP, EVAP, TMAX Y TMIN todas de tipo String).

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19574 entries, 0 to 19573
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   FECHA   19574 non-null  str
 1   PRECIP  19534 non-null  float64
 2   EVAP    19302 non-null  float64
 3   TMAX    19569 non-null  float64
 4   TMIN    19568 non-null  float64
dtypes: float64(4), str(1)
memory usage: 764.7 KB

In [75]:
df.shape

(19574, 5)

**Cada columna esta compuesta por:**  
**1.-Fecha:** fecha en dia, mes y año de la muestra.  
**2.-Precip:** precipitacion en milimietros de la muestra.  
**3.-Evap:** evaporacion en milimietros de la muestra.  
**4.-TMAX:** temperatura maxima en grados celsius de la muestra.  
**5.-TMIN** temperatura minima en grados celcius de la muestra.  


Las primeras 10 columnas muestran una precipitacion de 0, evaporacion en nulos, TMAX y TMIN muestran la temperatura maxima y minima en la fecha correspondiente.

In [65]:
df.head(10)

        FECHA PRECIP  EVAP  TMAX  TMIN
0  01/01/1961      0  Nulo    25    13
1  02/01/1961      0  Nulo  27.5    14
2  03/01/1961      0  Nulo    31    11
3  04/01/1961      0  Nulo    32    13
4  05/01/1961      0  Nulo    29    14
5  06/01/1961      0  Nulo    24  14.5
6  07/01/1961      0  Nulo  28.5    10
7  08/01/1961      0  Nulo    32    12
8  09/01/1961      0  Nulo  33.5    11
9  10/01/1961      0  Nulo  32.5   9.5

A diferencia de los primeros 10 registros, los ultimos 10 si cuentan con una precipitacion y evaporacion ademas de la temperatura maxima y minima.

In [76]:
df.tail(10)

            FECHA  PRECIP  EVAP  TMAX  TMIN
19564  22/07/2018     0.0   5.0  37.0  23.0
19565  23/07/2018     0.0   5.2  38.0  20.0
19566  24/07/2018     9.0   4.8  35.0  23.0
19567  25/07/2018     0.0   3.3  36.0  23.5
19568  26/07/2018     3.0   4.5  32.0  23.5
19569  27/07/2018     2.3   0.6  37.0  19.0
19570  28/07/2018     9.8   3.7  37.0  23.5
19571  29/07/2018     6.0   3.3  35.0  20.0
19572  30/07/2018    48.0   6.0  36.0  22.0
19573  31/07/2018     2.0   3.7  34.0  22.0

In [77]:
df.isnull().sum()

FECHA       0
PRECIP     40
EVAP      272
TMAX        5
TMIN        6
dtype: int64

El data frame cuenta con 19574 registros. **Fecha tiene todos sus registros unicos** esto significa que no existen fechas repetidas.

In [78]:
df.nunique()

FECHA     19574
PRECIP      492
EVAP        134
TMAX         59
TMIN         62
dtype: int64