# Exploracion de la estructura de los datos.
Lo primero que hicimos fue analizar y explorar los datos y la estructura del archivo mediante diferentes funciones de la libreria pandas.  

**Funciones y atributos utilizados:**  
**1.-read_csv:** Lectura del archivo mediante pandas.  
**2.- Skiprows:** Realiza saltos de linea del archivo. Lo utilizamos ya que las primeras lineas del txt tienen informacion adicional al Data Frame. Los registros comienzan en la linea 20.  
**3.- Skipfooter:** Al contrario de skiprows, skipfooter hace los saltos empezando de la ultima linea del archivo. Lo utilizamos ya que el ultimo registro tiene guiones en vez de datos.  
**4.- Names:** Mediante una lista asigna los nombres de las columnas.  
**5.- Sep:** Se utiliza para definir un delimitador entre columnas. Lo utilizamos ya que pandas tomaba las columnas de names como columnas independientes y les asignaba nulos a todos los registros. r (raw) indica que debe tomar todos los caracteres como datos, \s+ es para los espacios en blanco.  
**6.-na_values** Sirve para indicar que una cadena es de tipo NaN. Le indicamos que los registros con el dato 'Nulo' contaran como nules. Esto solo para el analisis del archivo por lo que no modifica el dataframe.  
**7.- info():** Muestra un resumen del dataframe. Datos como el numero de registros, nombres de columna, tipos de dato, cantidad de nulos etc.  
**8.- shape:** Devuelve una tupla con las dimensiones del data frame (numero de filas y columnas).  
**9.- head():** Regresa las primeras filas del data frame.  
**10.- tail():** Muestra las ultimas filas del data frame.  
**11.- isnull().sum():** Hace la suma de todos los nulos por cada columna tambien muestra tipo de dato.  
**12.- nunique():** Devuelve la cantidad de registors unicos por cada columna.

Lectura de archivos mediante pandas:

In [82]:
#Importacion de pandas y lectura del archivo.
import pandas as pd
df=pd.read_csv('Dataset/25001.txt',
skiprows=19, #saltamos las primeras 18 lineas del archivo
skipfooter=1,#saltamos la ultima linea 
names=['FECHA','PRECIP','EVAP','TMAX','TMIN'] , #Nombres de las columnas 
sep=r'\s+',#Separamos las columnas correctamente 
na_values='Nulo', #Asignamos como nulos los datos que contengan 'Nulo'
) 
df

C:\Users\luis_\AppData\Local\Temp\ipykernel_28120\846521548.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df=pd.read_csv('Dataset/25001.txt',

            FECHA  PRECIP  EVAP  TMAX  TMIN
0      01/01/1961     0.0   NaN  25.0  13.0
1      02/01/1961     0.0   NaN  27.5  14.0
2      03/01/1961     0.0   NaN  31.0  11.0
3      04/01/1961     0.0   NaN  32.0  13.0
4      05/01/1961     0.0   NaN  29.0  14.0
...           ...     ...   ...   ...   ...
19569  27/07/2018     2.3   0.6  37.0  19.0
19570  28/07/2018     9.8   3.7  37.0  23.5
19571  29/07/2018     6.0   3.3  35.0  20.0
19572  30/07/2018    48.0   6.0  36.0  22.0
19573  31/07/2018     2.0   3.7  34.0  22.0

[19574 rows x 5 columns]

El Data Frame tiene un total 19574 registros, 5 columnas (FECHA, PRECIP, EVAP, TMAX Y TMIN todas de tipo String).

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19574 entries, 0 to 19573
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   FECHA   19574 non-null  object
 1   PRECIP  19534 non-null  float64
 2   EVAP    19302 non-null  float64
 3   TMAX    19569 non-null  float64
 4   TMIN    19568 non-null  float64
dtypes: float64(4), object(1)
memory usage: 764.7+ KB

In [4]:
df.shape

(19574, 5)

**Cada columna esta compuesta por:**  
**1.-Fecha:** fecha en dia, mes y año de la muestra.  
**2.-Precip:** precipitacion en milimietros de la muestra.  
**3.-Evap:** evaporacion en milimietros de la muestra.  
**4.-TMAX:** temperatura maxima en grados celsius de la muestra.  
**5.-TMIN** temperatura minima en grados celcius de la muestra.  


Las primeras 10 columnas muestran una precipitacion de 0, evaporacion en nulos, TMAX y TMIN muestran la temperatura maxima y minima en la fecha correspondiente.

In [5]:
df.head(10)

        FECHA  PRECIP  EVAP  TMAX  TMIN
0  01/01/1961     0.0   NaN  25.0  13.0
1  02/01/1961     0.0   NaN  27.5  14.0
2  03/01/1961     0.0   NaN  31.0  11.0
3  04/01/1961     0.0   NaN  32.0  13.0
4  05/01/1961     0.0   NaN  29.0  14.0
5  06/01/1961     0.0   NaN  24.0  14.5
6  07/01/1961     0.0   NaN  28.5  10.0
7  08/01/1961     0.0   NaN  32.0  12.0
8  09/01/1961     0.0   NaN  33.5  11.0
9  10/01/1961     0.0   NaN  32.5   9.5

A diferencia de los primeros 10 registros, los ultimos 10 si cuentan con una precipitacion y evaporacion ademas de la temperatura maxima y minima.

In [76]:
df.tail(10)

            FECHA  PRECIP  EVAP  TMAX  TMIN
19564  22/07/2018     0.0   5.0  37.0  23.0
19565  23/07/2018     0.0   5.2  38.0  20.0
19566  24/07/2018     9.0   4.8  35.0  23.0
19567  25/07/2018     0.0   3.3  36.0  23.5
19568  26/07/2018     3.0   4.5  32.0  23.5
19569  27/07/2018     2.3   0.6  37.0  19.0
19570  28/07/2018     9.8   3.7  37.0  23.5
19571  29/07/2018     6.0   3.3  35.0  20.0
19572  30/07/2018    48.0   6.0  36.0  22.0
19573  31/07/2018     2.0   3.7  34.0  22.0

In [77]:
df.isnull().sum()

FECHA       0
PRECIP     40
EVAP      272
TMAX        5
TMIN        6
dtype: int64

El data frame cuenta con 19574 registros. **Fecha tiene todos sus registros unicos** esto significa que no existen fechas repetidas.

In [78]:
df.nunique()

FECHA     19574
PRECIP      492
EVAP        134
TMAX         59
TMIN         62
dtype: int64

# Nombrar el archivo leyendolo.
Se busca modificar el nombre del archivo colocando clave, nombre y fecha como en el siguiente ejemplo:  
CVE  _ NOMBRE _  FECHA   
25001_GVE01_14052025   

para esto utilizamos la funcion open() de python la cual nos permite leer el archivo. Despues declaramos las lineas y las separamos para obtener los datos clave y nombrar el archivo.

Funciones utilizadas:

Primeramente abrimos el archivo, creamos una lista con las lineas del archivo y despues creamos una variable para clave, nombre y fecha.
Estas variables las construimos primeramente diviendo el numero de linea correspondiente separada por dos puntos con split(). Despues con strip() agarramos el dato que nombrara al archivo sin caracteres especiales. Ejemplo:

linea antes del procesamiento:  
ESTACION  : 25001  
linea despues del procesamiento:  
25001

In [ ]:
with open('Dataset/25001.txt', 'r', encoding='utf-8') as f:
    lineas = f.readlines() #readlines regresa una lista de lineas del archivo 
    clave = lineas[4].split(':')[1].strip() # Dividimos la linea 5 del archivo separando
    nombre = lineas[5].split(':')[1].strip() 
    fecha = lineas[15].split(':')[1].strip().replace('/','')#replace para quitar los / en la fecha y cumplir con el formato

    nombre_archivo=clave+'_'+nombre+'_'+fecha

    print(nombre_archivo)

25001_ACATITAN_06042020

# Proceso de Transformación y Limpieza de Datos
En esta etapa, convertimos los datos crudos en un formato apto para el análisis estadístico. El proceso se ha dividido en funciones específicas que permiten un manejo controlado de la información.

### Librerías y Métodos Utilizados:
* **Pandas:** Utilizada para la estructuración y limpieza del DataFrame.
* **to_datetime (errors='coerce'):** Transforma la columna de fechas. El uso de `coerce` es fundamental para la **limpieza**, ya que convierte automáticamente cualquier texto inválido (como títulos o guiones) en valores `NaT` (Not a Time), evitando errores de ejecución.
* **dropna():** Elimina las filas que no contienen fechas válidas, asegurando que solo trabajemos con registros cronológicos reales.
* **to_numeric:** Convierte las columnas de medición (Precipitación, Evaporación, etc.) de texto a números decimales para permitir el cálculo de métricas.

In [7]:
def transformar_datos(df):
    """
    Función modular para convertir tipos de datos y eliminar basura de texto.
    """
    # Convertimos la fecha. Si hay algo que no sea fecha, lo marca como vacío (NaT)
    # errors='coerce' marca como NaT cualquier dato que no sea una fecha (ej. guiones)
    df['FECHA'] = pd.to_datetime(df['FECHA'], dayfirst=True, errors='coerce')

    # Borramos las filas que quedaron vacías en la columna de Fecha (títulos o guiones)
    # Esto limpia definitivamente los encabezados repetidos y líneas divisorias
    df = df.dropna(subset=['FECHA'])

    # Convertimos las columnas de datos a números 
    cols_num = ['PRECIP', 'EVAP', 'TMAX', 'TMIN']
    df[cols_num] = df[cols_num].apply(pd.to_numeric, errors='coerce')
    
    return df

# Llamada a la función
df = transformar_datos(df)
print("Transformación de tipos completada.")
df.head()

Transformación de tipos completada.

       FECHA  PRECIP  EVAP  TMAX  TMIN
0 1961-01-01     0.0   NaN  25.0  13.0
1 1961-01-02     0.0   NaN  27.5  14.0
2 1961-01-03     0.0   NaN  31.0  11.0
3 1961-01-04     0.0   NaN  32.0  13.0
4 1961-01-05     0.0   NaN  29.0  14.0

### Tratamiento de Valores Faltantes (Nulos)
Para garantizar la integridad del Análisis Exploratorio de Datos (EDA), es necesario tratar los valores nulos identificados previamente.

**Decisión de Limpieza:**
Se ha optado por **rellenar los valores nulos con la media (promedio)** de cada columna.

In [12]:
def aplicar_limpieza_nulos(df):
    """
    Rellena los espacios vacíos con el promedio de la columna.
    Justificado por la necesidad de mantener la tendencia estadística.
    """
    cols_num = ['PRECIP', 'EVAP', 'TMAX', 'TMIN']
    
    # Rellenamos nulos con la media de cada columna respectiva
    df[cols_num] = df[cols_num].fillna(df[cols_num].mean())
    
    return df

# Aplicamos la limpieza
df = aplicar_limpieza_nulos(df)
print("Limpieza de nulos con la media finalizada.")
# Verificamos que ya no existan nulos
df.isnull().sum()

Limpieza de nulos con la media finalizada.

FECHA     0
PRECIP    0
EVAP      0
TMAX      0
TMIN      0
dtype: int64

# Análisis Exploratorio de Datos (EDA)
En esta sección final, generamos las métricas estadísticas que solicita la rúbrica. El objetivo es identificar los valores máximos, mínimos, la media y la mediana de las variables climáticas registradas en la estación.

**Funciones Utilizadas:**
* **describe():** Para obtener un panorama estadístico global.
* **mean(), median(), max(), min():** Para cumplir con la identificación específica de métricas requeridas en el proyecto.

In [ ]:
def ejecutar_eda(df):
    """
    Calcula y muestra las estadísticas principales del dataset.
    """
    # Elegimos las columnas a utilizar para calcular los datos
    cols_num = ['PRECIP', 'EVAP', 'TMAX', 'TMIN']
    
    print("--- RESUMEN ESTADÍSTICO ---")
    # Se muestra el resumen estadístico general de las columnas numéricas
    display(df[cols_num].describe())
    
    print("\n--- MÉTRICAS ESPECÍFICAS SOLICITADAS ---")
    # Creamos un DataFrame para mostrar las métricas específicas de media, mediana, máximo y mínimo
    stats_resumen = pd.DataFrame({
        'Media (Promedio)': df[cols_num].mean(), # Calculamos la media de cada columna numérica
        'Mediana': df[cols_num].median(), # Calculamos la mediana de cada columna numérica
        'Valor máximo': df[cols_num].max(), # Calculamos el valor máximo de cada columna numérica
        'Valor mínimo': df[cols_num].min() # Calculamos el valor mínimo de cada columna numérica
    })
    display(stats_resumen)

# Ejecutamos el análisis final
ejecutar_eda(df)

--- RESUMEN ESTADÍSTICO ---

             PRECIP          EVAP          TMAX          TMIN
count  19534.000000  19302.000000  19569.000000  19568.000000
mean       2.217452      4.882157     34.468808     16.657420
std        9.015782      2.279340      3.430054      6.248605
min        0.000000      0.000000     18.000000     -2.500000
25%        0.000000      3.200000     32.500000     11.000000
50%        0.000000      4.500000     35.000000     16.500000
75%        0.000000      6.500000     37.000000     23.000000
max      217.400000     15.600000     45.500000     29.000000

--- MÉTRICAS ESPECÍFICAS SOLICITADAS ---

        Media (Promedio)  Mediana  Máximo Histórico  Mínimo Histórico
PRECIP          2.217452      0.0             217.4               0.0
EVAP            4.882157      4.5              15.6               0.0
TMAX           34.468808     35.0              45.5              18.0
TMIN           16.657420     16.5              29.0              -2.5